modLoader="javafml"
loaderVersion="[61,)"
license="MIT"

[[mods]]
modId="mcbutitremembersyourdeaths"
version="0.0.3"
displayName="MC But It Remembers Your Deaths"
description="A Minecraft mod that gives funny messages when you die repeatedly."
