modLoader="javafml"
loaderVersion="[61,)"
license="MIT"

[[mods]]
modId="mcbutitremembersyourdeaths"
version="1.0.0"
displayName="MC But It Remembers Your Deaths"
description="A Minecraft mod that gives funny messages when you die repeatedly."
